In [6]:
import pandas as pd
import numpy as np

In [8]:


df = pd.read_excel("C:\\Users\\Legion\\Downloads\\SFT_Contextual_10000_updated.xlsx")
print("Dataset loaded successfully!")
df

Dataset loaded successfully!

,id,domain,instruction,input,output,source
0,8bcd7516-264f-4d52-8d24-223a4519d71b,finance,Calculate compound interest from the details b...,"Principal: $1,000, Rate: 5%, Time: 3 years",Using the compound interest formula A = P(1 + ...,synthetic
1,02b6b474-7e0a-4d26-b58d-26caeda87200,marketing,Suggest a campaign slogan from this product de...,A smartwatch that monitors your health in real...,"""Your Health, Live. Your Performance, Elevated...",human-curated
2,13741ac3-de4c-4f18-ad04-0f9aca9e8434,productivity,Create a daily schedule using this task list.,"Write report, team meeting, client call, gym, ...",Here is a suggested daily schedule:\n8:00–9:30...,synthetic
3,01de4e88-64aa-45f3-befb-c077e83e5418,sports,Summarize the game report.,Team A scored 3 goals in the second half to wi...,"Team A came from behind, scoring all 3 of thei...",synthetic
4,b04b6a43-d366-4b48-bbb7-9f2e075205e2,law,Summarize this legal paragraph.,The Fourth Amendment protects citizens against...,The Fourth Amendment safeguards individuals fr...,human-curated
...,...,...,...,...,...,...
9995,28b08e2c-1491-4bcb-9081-f2d9c3edd813,healthcare,Summarize the patient's condition from the not...,"Patient reports shortness of breath, fatigue, ...",The patient has presented with a 3-day history...,human-curated
9996,c438da14-6945-46d4-b5e1-109cbdf6365d,education,Summarize the paragraph below.,The Industrial Revolution marked a major turni...,The Industrial Revolution was a pivotal period...,human-curated
9997,93e27108-959a-40cb-abec-0a03b0ea07fa,sports,Summarize the game report.,Team A scored 3 goals in the second half to wi...,"Team A came from behind, scoring all 3 of thei...",human-curated
9998,0cc166fa-7b81-407c-bbf5-57df5fec39a7,law,Explain if the scenario below qualifies as neg...,A store employee mopped the floor but failed t...,This likely qualifies as negligence. The store...,human-curated
9999,078765ed-2d01-4932-9c3a-f0e24f300db5,marketing,Analyze this ad copy for effectiveness.,Buy now! Best prices of the year. Limited time...,This ad copy uses classic urgency and scarcity...,human-curated

In [9]:
#datasize visualization
print("Dataset Shape:", df.shape)

print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

Dataset Shape: (10000, 6)
Total Rows: 10000
Total Columns: 6

In [10]:
#top 5 rows
df.head()

,id,domain,instruction,input,output,source
0,8bcd7516-264f-4d52-8d24-223a4519d71b,finance,Calculate compound interest from the details b...,"Principal: $1,000, Rate: 5%, Time: 3 years",Using the compound interest formula A = P(1 + ...,synthetic
1,02b6b474-7e0a-4d26-b58d-26caeda87200,marketing,Suggest a campaign slogan from this product de...,A smartwatch that monitors your health in real...,"""Your Health, Live. Your Performance, Elevated...",human-curated
2,13741ac3-de4c-4f18-ad04-0f9aca9e8434,productivity,Create a daily schedule using this task list.,"Write report, team meeting, client call, gym, ...",Here is a suggested daily schedule:\n8:00–9:30...,synthetic
3,01de4e88-64aa-45f3-befb-c077e83e5418,sports,Summarize the game report.,Team A scored 3 goals in the second half to wi...,"Team A came from behind, scoring all 3 of thei...",synthetic
4,b04b6a43-d366-4b48-bbb7-9f2e075205e2,law,Summarize this legal paragraph.,The Fourth Amendment protects citizens against...,The Fourth Amendment safeguards individuals fr...,human-curated

In [11]:
#dataset columns visualization
print("Dataset Columns:")

for column in df.columns:
    print("-", column)

Dataset Columns:
- id
- domain
- instruction
- input
- output
- source

In [12]:
#checking data types of each column
print(df.dtypes)

id             object
domain         object
instruction    object
input          object
output         object
source         object
dtype: object

In [13]:
missing_values = df.isnull().sum()

print("Missing Values in Each Column:")
print(missing_values)

Missing Values in Each Column:
id             0
domain         0
instruction    0
input          0
output         0
source         0
dtype: int64

In [14]:
duplicate_rows = df.duplicated().sum()

print("Total Duplicate Rows:", duplicate_rows)

Total Duplicate Rows: 0

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           10000 non-null  object
 1   domain       10000 non-null  object
 2   instruction  10000 non-null  object
 3   input        10000 non-null  object
 4   output       10000 non-null  object
 5   source       10000 non-null  object
dtypes: object(6)
memory usage: 468.9+ KB

In [16]:
print("SFT DATASET INITIAL SUMMARY")

print(f"Total Rows: {df.shape[0]}")
print(f"Total Columns: {df.shape[1]}")

print("\nColumn Names:")
print(df.columns.tolist())

print("\nTotal Missing Values:")
print(df.isnull().sum().sum())

print("\nTotal Duplicate Rows:")
print(df.duplicated().sum())

SFT DATASET INITIAL SUMMARY
Total Rows: 10000
Total Columns: 6

Column Names:
['id', 'domain', 'instruction', 'input', 'output', 'source']

Total Missing Values:
0

Total Duplicate Rows:
0

In [17]:
# Save the original dataset in CSV format

output_path = "../data/raw/sft_dataset.csv"

df.to_csv(
    output_path,
    index=False
)

print("Original dataset saved as sft_dataset.csv")

Original dataset saved as sft_dataset.csv