In [2]:
import pandas as pd
import numpy as np

In [3]:
# Load the SFT dataset


df = pd.read_excel("C:\\Users\\Legion\\Downloads\\SFT_Contextual_10000_updated.xlsx")
print("Dataset loaded successfully")
df

Dataset loaded successfully

,id,domain,instruction,input,output,source
0,8bcd7516-264f-4d52-8d24-223a4519d71b,finance,Calculate compound interest from the details b...,"Principal: $1,000, Rate: 5%, Time: 3 years",Using the compound interest formula A = P(1 + ...,synthetic
1,02b6b474-7e0a-4d26-b58d-26caeda87200,marketing,Suggest a campaign slogan from this product de...,A smartwatch that monitors your health in real...,"""Your Health, Live. Your Performance, Elevated...",human-curated
2,13741ac3-de4c-4f18-ad04-0f9aca9e8434,productivity,Create a daily schedule using this task list.,"Write report, team meeting, client call, gym, ...",Here is a suggested daily schedule:\n8:00–9:30...,synthetic
3,01de4e88-64aa-45f3-befb-c077e83e5418,sports,Summarize the game report.,Team A scored 3 goals in the second half to wi...,"Team A came from behind, scoring all 3 of thei...",synthetic
4,b04b6a43-d366-4b48-bbb7-9f2e075205e2,law,Summarize this legal paragraph.,The Fourth Amendment protects citizens against...,The Fourth Amendment safeguards individuals fr...,human-curated
...,...,...,...,...,...,...
9995,28b08e2c-1491-4bcb-9081-f2d9c3edd813,healthcare,Summarize the patient's condition from the not...,"Patient reports shortness of breath, fatigue, ...",The patient has presented with a 3-day history...,human-curated
9996,c438da14-6945-46d4-b5e1-109cbdf6365d,education,Summarize the paragraph below.,The Industrial Revolution marked a major turni...,The Industrial Revolution was a pivotal period...,human-curated
9997,93e27108-959a-40cb-abec-0a03b0ea07fa,sports,Summarize the game report.,Team A scored 3 goals in the second half to wi...,"Team A came from behind, scoring all 3 of thei...",human-curated
9998,0cc166fa-7b81-407c-bbf5-57df5fec39a7,law,Explain if the scenario below qualifies as neg...,A store employee mopped the floor but failed t...,This likely qualifies as negligence. The store...,human-curated
9999,078765ed-2d01-4932-9c3a-f0e24f300db5,marketing,Analyze this ad copy for effectiveness.,Buy now! Best prices of the year. Limited time...,This ad copy uses classic urgency and scarcity...,human-curated

In [4]:
# Display the first five rows

df.head()

,id,domain,instruction,input,output,source
0,8bcd7516-264f-4d52-8d24-223a4519d71b,finance,Calculate compound interest from the details b...,"Principal: $1,000, Rate: 5%, Time: 3 years",Using the compound interest formula A = P(1 + ...,synthetic
1,02b6b474-7e0a-4d26-b58d-26caeda87200,marketing,Suggest a campaign slogan from this product de...,A smartwatch that monitors your health in real...,"""Your Health, Live. Your Performance, Elevated...",human-curated
2,13741ac3-de4c-4f18-ad04-0f9aca9e8434,productivity,Create a daily schedule using this task list.,"Write report, team meeting, client call, gym, ...",Here is a suggested daily schedule:\n8:00–9:30...,synthetic
3,01de4e88-64aa-45f3-befb-c077e83e5418,sports,Summarize the game report.,Team A scored 3 goals in the second half to wi...,"Team A came from behind, scoring all 3 of thei...",synthetic
4,b04b6a43-d366-4b48-bbb7-9f2e075205e2,law,Summarize this legal paragraph.,The Fourth Amendment protects citizens against...,The Fourth Amendment safeguards individuals fr...,human-curated

In [6]:
# Display the dataset shape

print("Total rows:", df.shape[0])

print("Total columns:", df.shape[1])

Total rows: 10000
Total columns: 6

In [7]:
# Display the dataset columns

print(df.columns.tolist())

['id', 'domain', 'instruction', 'input', 'output', 'source']

In [8]:
# Check whether all required columns are available

required_columns = [
    "id",
    "domain",
    "instruction",
    "input",
    "output",
    "source"
]

missing_columns = []

for column in required_columns:
    if column not in df.columns:
        missing_columns.append(column)

if len(missing_columns) == 0:
    print("All required columns are available")
else:
    print("Missing columns:")
    print(missing_columns)

All required columns are available

In [9]:
# Count missing values in each column

missing_values = df.isnull().sum()

print(missing_values)

id             0
domain         0
instruction    0
input          0
output         0
source         0
dtype: int64

In [10]:
# Check empty values in text columns

text_columns = [
    "domain",
    "instruction",
    "input",
    "output",
    "source"
]

empty_counts = {}

for column in text_columns:

    empty_count = (
        df[column]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    empty_counts[column] = empty_count

print(empty_counts)

{'domain': 0, 'instruction': 0, 'input': 0, 'output': 0, 'source': 0}

In [11]:
# Count exact duplicate rows

duplicate_rows = df.duplicated().sum()

print("Total duplicate rows:", duplicate_rows)

Total duplicate rows: 0

In [12]:
# Check duplicate IDs

duplicate_ids = df["id"].duplicated().sum()

print("Duplicate IDs:", duplicate_ids)

Duplicate IDs: 0

In [13]:
# Check duplicate instructions

duplicate_instructions = (
    df["instruction"]
    .duplicated()
    .sum()
)

print("Duplicate instructions:", duplicate_instructions)

Duplicate instructions: 9980

In [14]:
# Check duplicate outputs

duplicate_outputs = (
    df["output"]
    .duplicated()
    .sum()
)

print("Duplicate outputs:", duplicate_outputs)

Duplicate outputs: 9980

In [15]:
# Check duplicate SFT samples

duplicate_samples = (
    df.duplicated(
        subset=[
            "instruction",
            "input",
            "output"
        ]
    )
    .sum()
)

print("Duplicate SFT samples:", duplicate_samples)

Duplicate SFT samples: 9980

In [16]:
# Count unique values in important columns

print("Unique instructions:", df["instruction"].nunique())

print("Unique inputs:", df["input"].nunique())

print("Unique outputs:", df["output"].nunique())

Unique instructions: 20
Unique inputs: 20
Unique outputs: 20

In [17]:
# Display unique instruction values

df["instruction"].unique()

array(['Calculate compound interest from the details below.',
       'Suggest a campaign slogan from this product description.',
       'Create a daily schedule using this task list.',
       'Summarize the game report.', 'Summarize this legal paragraph.',
       'Identify the psychological condition based on the description.',
       'Suggest travel tips from the following user notes.',
       'Analyze the training plan below.',
       'Interpret the dream scenario provided below.',
       'Formulate three quiz questions from the following text.',
       'Analyze this financial summary and suggest improvements.',
       'Identify productivity issues from the following log.',
       'Explain if the scenario below qualifies as negligence.',
       "Summarize the patient's condition from the notes below.",
       'What are the possible diagnoses based on these symptoms?',
       'Summarize the paragraph below.',
       'What does the following Python code do?',
       'Fix the error in the following code snippet.',
       'Analyze this ad copy for effectiveness.',
       'Plan a 5-day itinerary from the info below.'], dtype=object)

In [18]:
# Count occurrences of each instruction

instruction_counts = (
    df["instruction"]
    .value_counts()
)

instruction_counts

instruction
What does the following Python code do?                           533
Summarize the patient's condition from the notes below.           529
Calculate compound interest from the details below.               521
Explain if the scenario below qualifies as negligence.            518
Fix the error in the following code snippet.                      512
Plan a 5-day itinerary from the info below.                       512
Identify productivity issues from the following log.              510
Create a daily schedule using this task list.                     505
Suggest a campaign slogan from this product description.          502
Analyze this financial summary and suggest improvements.          499
What are the possible diagnoses based on these symptoms?          497
Analyze this ad copy for effectiveness.                           495
Identify the psychological condition based on the description.    492
Suggest travel tips from the following user notes.                490
Interpret the dream scenario provided below.                      490
Summarize the game report.                                        489
Formulate three quiz questions from the following text.           480
Analyze the training plan below.                                  479
Summarize this legal paragraph.                                   475
Summarize the paragraph below.                                    472
Name: count, dtype: int64

In [19]:
# Display the first ten rows

df[
    [
        "id",
        "instruction",
        "input",
        "output"
    ]
].head(10)

,id,instruction,input,output
0,8bcd7516-264f-4d52-8d24-223a4519d71b,Calculate compound interest from the details b...,"Principal: $1,000, Rate: 5%, Time: 3 years",Using the compound interest formula A = P(1 + ...
1,02b6b474-7e0a-4d26-b58d-26caeda87200,Suggest a campaign slogan from this product de...,A smartwatch that monitors your health in real...,"""Your Health, Live. Your Performance, Elevated..."
2,13741ac3-de4c-4f18-ad04-0f9aca9e8434,Create a daily schedule using this task list.,"Write report, team meeting, client call, gym, ...",Here is a suggested daily schedule:\n8:00–9:30...
3,01de4e88-64aa-45f3-befb-c077e83e5418,Summarize the game report.,Team A scored 3 goals in the second half to wi...,"Team A came from behind, scoring all 3 of thei..."
4,b04b6a43-d366-4b48-bbb7-9f2e075205e2,Summarize this legal paragraph.,The Fourth Amendment protects citizens against...,The Fourth Amendment safeguards individuals fr...
5,005f3f91-e4ab-41cd-a8ab-3f7f3b778066,Identify the psychological condition based on ...,"The person experiences mood swings, anxiety, a...","These symptoms — mood swings, anxiety, and pro..."
6,a63eda30-6f6b-44dc-94f2-21da354ae5fc,Suggest travel tips from the following user no...,"I often forget essentials, overspend, and get ...","Based on your notes, here are targeted tips: 1..."
7,e62673f0-8c0d-4cb0-8580-51e06058704f,Create a daily schedule using this task list.,"Write report, team meeting, client call, gym, ...",Here is a suggested daily schedule:\n8:00–9:30...
8,a332be40-695c-4187-84e6-41bff5be5691,Analyze the training plan below.,"Monday: Cardio, Tuesday: Weights, Wednesday: R...",This plan follows a sound structure by alterna...
9,9251c1c1-0cfc-4627-8b3e-2587c1a3cd75,Interpret the dream scenario provided below.,I was flying and then falling endlessly into d...,"In common dream symbolism, flying often repres..."

In [20]:
duplicate_samples = df.duplicated(
    subset=[
        "instruction",
        "input",
        "output"
    ]
).sum()

print("Duplicate SFT samples:", duplicate_samples)

Duplicate SFT samples: 9980

In [21]:
# Calculate instruction length using word count

df["instruction_length"] = (
    df["instruction"]
    .astype(str)
    .str.split()
    .str.len()
)

df[
    [
        "instruction",
        "instruction_length"
    ]
].head()

                                         instruction  instruction_length
0  Calculate compound interest from the details b...                   7
1  Suggest a campaign slogan from this product de...                   8
2      Create a daily schedule using this task list.                   8
3                         Summarize the game report.                   4
4                    Summarize this legal paragraph.                   4

In [22]:
# Calculate input length using word count

df["input_length"] = (
    df["input"]
    .astype(str)
    .str.split()
    .str.len()
)

df[
    [
        "input",
        "input_length"
    ]
].head()

                                               input  input_length
0         Principal: $1,000, Rate: 5%, Time: 3 years             7
1  A smartwatch that monitors your health in real...            11
2  Write report, team meeting, client call, gym, ...             9
3  Team A scored 3 goals in the second half to wi...            15
4  The Fourth Amendment protects citizens against...             8

In [23]:
# Calculate output length using word count

df["output_length"] = (
    df["output"]
    .astype(str)
    .str.split()
    .str.len()
)

df[
    [
        "output",
        "output_length"
    ]
].head()

                                              output  output_length
0  Using the compound interest formula A = P(1 + ...             52
1  "Your Health, Live. Your Performance, Elevated...             35
2  Here is a suggested daily schedule:\n8:00–9:30...             50
3  Team A came from behind, scoring all 3 of thei...             35
4  The Fourth Amendment safeguards individuals fr...             32

In [24]:
# Display text length statistics

length_statistics = df[
    [
        "instruction_length",
        "input_length",
        "output_length"
    ]
].describe()

length_statistics

       instruction_length  input_length  output_length
count        10000.000000  10000.000000   10000.000000
mean             6.928300      9.551200      50.366400
std              1.493446      3.059986      13.496717
min              4.000000      4.000000      32.000000
25%              6.000000      7.000000      40.000000
50%              8.000000      9.000000      50.000000
75%              8.000000     11.000000      63.000000
max              9.000000     15.000000      81.000000

In [25]:
# Count very short instructions

minimum_instruction_length = 3

short_instructions = (
    df["instruction_length"]
    < minimum_instruction_length
).sum()

print(
    "Very short instructions:",
    short_instructions
)

Very short instructions: 0

In [26]:
# Count very short inputs

minimum_input_length = 3

short_inputs = (
    df["input_length"]
    < minimum_input_length
).sum()

print(
    "Very short inputs:",
    short_inputs
)

Very short inputs: 0

In [27]:
# Count very short outputs

minimum_output_length = 5

short_outputs = (
    df["output_length"]
    < minimum_output_length
).sum()

print(
    "Very short outputs:",
    short_outputs
)

Very short outputs: 0

In [28]:
# Count very long outputs

maximum_output_length = 500

long_outputs = (
    df["output_length"]
    > maximum_output_length
).sum()

print(
    "Very long outputs:",
    long_outputs
)

Very long outputs: 0

In [29]:
# Display very short output samples

df[
    df["output_length"] < minimum_output_length
][
    [
        "id",
        "instruction",
        "input",
        "output",
        "output_length"
    ]
].head(10)

Empty DataFrame
Columns: [id, instruction, input, output, output_length]
Index: []

In [30]:
# Display all unique domain values

unique_domains = (
    df["domain"]
    .astype(str)
    .str.strip()
    .sort_values()
    .unique()
)

print("Total unique domains:", len(unique_domains))

print(unique_domains)

Total unique domains: 10
['code' 'education' 'finance' 'healthcare' 'law' 'marketing'
 'productivity' 'psychology' 'sports' 'travel']

In [31]:
# Count samples in each domain

domain_counts = (
    df["domain"]
    .astype(str)
    .str.strip()
    .value_counts()
)

domain_counts

domain
code            1045
healthcare      1026
finance         1020
productivity    1015
travel          1002
marketing        997
law              993
psychology       982
sports           968
education        952
Name: count, dtype: int64

In [32]:
# Check empty domain values

empty_domains = (
    df["domain"]
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

print("Empty domains:", empty_domains)

Empty domains: 0

In [33]:
# Check domain values with leading or trailing spaces

domain_values = (
    df["domain"]
    .astype(str)
)

domains_with_extra_spaces = (
    domain_values
    .ne(domain_values.str.strip())
    .sum()
)

print(
    "Domains with extra spaces:",
    domains_with_extra_spaces
)

Domains with extra spaces: 0

In [34]:
# Calculate domain distribution percentage

domain_percentage = (
    df["domain"]
    .astype(str)
    .str.strip()
    .value_counts(
        normalize=True
    )
    * 100
)

domain_percentage.round(2)

domain
code            10.45
healthcare      10.26
finance         10.20
productivity    10.15
travel          10.02
marketing        9.97
law              9.93
psychology       9.82
sports           9.68
education        9.52
Name: proportion, dtype: float64

In [35]:
# Identify the largest and smallest domains

largest_domain = (
    domain_counts.idxmax()
)

largest_domain_count = (
    domain_counts.max()
)

smallest_domain = (
    domain_counts.idxmin()
)

smallest_domain_count = (
    domain_counts.min()
)

print(
    "Largest domain:",
    largest_domain
)

print(
    "Largest domain sample count:",
    largest_domain_count
)

print(
    "Smallest domain:",
    smallest_domain
)

print(
    "Smallest domain sample count:",
    smallest_domain_count
)

Largest domain: code
Largest domain sample count: 1045
Smallest domain: education
Smallest domain sample count: 952

In [36]:
# Calculate the domain balance ratio

domain_balance_ratio = (
    smallest_domain_count
    / largest_domain_count
)

print(
    "Domain balance ratio:",
    round(
        domain_balance_ratio,
        2
    )
)

Domain balance ratio: 0.91

In [37]:
# Display all unique source values

unique_sources = (
    df["source"]
    .astype(str)
    .str.strip()
    .unique()
)

print("Total unique sources:", len(unique_sources))

print(unique_sources)

Total unique sources: 2
['synthetic' 'human-curated']

In [38]:
# Count samples from each source

source_counts = (
    df["source"]
    .astype(str)
    .str.strip()
    .value_counts()
)

source_counts

source
synthetic        5024
human-curated    4976
Name: count, dtype: int64

In [39]:
# Check empty source values

empty_sources = (
    df["source"]
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

print("Empty sources:", empty_sources)

Empty sources: 0

In [40]:
# Check source values with extra spaces

source_values = (
    df["source"]
    .astype(str)
)

sources_with_extra_spaces = (
    source_values
    .ne(source_values.str.strip())
    .sum()
)

print(
    "Sources with extra spaces:",
    sources_with_extra_spaces
)

Sources with extra spaces: 0

In [41]:
# Check the number of samples from each source

print(
    "Largest source:",
    source_counts.idxmax()
)

print(
    "Largest source count:",
    source_counts.max()
)

print(
    "Smallest source:",
    source_counts.idxmin()
)

print(
    "Smallest source count:",
    source_counts.min()
)

Largest source: synthetic
Largest source count: 5024
Smallest source: human-curated
Smallest source count: 4976

In [42]:
# Calculate total missing values

total_missing_values = df.isnull().sum().sum()

print("Total missing values:", total_missing_values)

Total missing values: 0

In [43]:
# Calculate total empty text values

total_empty_values = (
    empty_counts["domain"]
    + empty_counts["instruction"]
    + empty_counts["input"]
    + empty_counts["output"]
    + empty_counts["source"]
)

print("Total empty text values:", total_empty_values)

Total empty text values: 0

In [44]:
# Create the quality check summary

quality_summary = pd.DataFrame({
    "Quality Check": [
        "Missing Values",
        "Empty Text Values",
        "Duplicate IDs",
        "Duplicate SFT Samples",
        "Very Short Instructions",
        "Very Short Inputs",
        "Very Short Outputs",
        "Very Long Outputs",
        "Empty Domains",
        "Domains With Extra Spaces",
        "Empty Sources",
        "Sources With Extra Spaces"
    ],
    "Issue Count": [
        total_missing_values,
        total_empty_values,
        duplicate_ids,
        duplicate_samples,
        short_instructions,
        short_inputs,
        short_outputs,
        long_outputs,
        empty_domains,
        domains_with_extra_spaces,
        empty_sources,
        sources_with_extra_spaces
    ]
})

quality_summary

                Quality Check  Issue Count
0              Missing Values            0
1           Empty Text Values            0
2               Duplicate IDs            0
3       Duplicate SFT Samples         9980
4     Very Short Instructions            0
5           Very Short Inputs            0
6          Very Short Outputs            0
7           Very Long Outputs            0
8               Empty Domains            0
9   Domains With Extra Spaces            0
10              Empty Sources            0
11  Sources With Extra Spaces            0

In [45]:
# Calculate issue percentage

quality_summary["Issue Percentage"] = (
    quality_summary["Issue Count"]
    / len(df)
    * 100
)

quality_summary["Issue Percentage"] = (
    quality_summary["Issue Percentage"]
    .round(2)
)

quality_summary

                Quality Check  Issue Count  Issue Percentage
0              Missing Values            0               0.0
1           Empty Text Values            0               0.0
2               Duplicate IDs            0               0.0
3       Duplicate SFT Samples         9980              99.8
4     Very Short Instructions            0               0.0
5           Very Short Inputs            0               0.0
6          Very Short Outputs            0               0.0
7           Very Long Outputs            0               0.0
8               Empty Domains            0               0.0
9   Domains With Extra Spaces            0               0.0
10              Empty Sources            0               0.0
11  Sources With Extra Spaces            0               0.0

In [46]:
# Assign quality status to each check

def get_issue_status(issue_count):

    if issue_count == 0:
        return "Passed"

    elif issue_count <= len(df) * 0.01:
        return "Minor Issue"

    elif issue_count <= len(df) * 0.05:
        return "Moderate Issue"

    else:
        return "Major Issue"


quality_summary["Status"] = (
    quality_summary["Issue Count"]
    .apply(get_issue_status)
)

quality_summary

                Quality Check  Issue Count  Issue Percentage       Status
0              Missing Values            0               0.0       Passed
1           Empty Text Values            0               0.0       Passed
2               Duplicate IDs            0               0.0       Passed
3       Duplicate SFT Samples         9980              99.8  Major Issue
4     Very Short Instructions            0               0.0       Passed
5           Very Short Inputs            0               0.0       Passed
6          Very Short Outputs            0               0.0       Passed
7           Very Long Outputs            0               0.0       Passed
8               Empty Domains            0               0.0       Passed
9   Domains With Extra Spaces            0               0.0       Passed
10              Empty Sources            0               0.0       Passed
11  Sources With Extra Spaces            0               0.0       Passed

In [47]:
# Display the final quality check report

print("SFT DATASET QUALITY CHECK REPORT")

print()

print("Total samples:", len(df))

print()

print(
    quality_summary.to_string(
        index=False
    )
)

SFT DATASET QUALITY CHECK REPORT

Total samples: 10000

            Quality Check  Issue Count  Issue Percentage      Status
           Missing Values            0               0.0      Passed
        Empty Text Values            0               0.0      Passed
            Duplicate IDs            0               0.0      Passed
    Duplicate SFT Samples         9980              99.8 Major Issue
  Very Short Instructions            0               0.0      Passed
        Very Short Inputs            0               0.0      Passed
       Very Short Outputs            0               0.0      Passed
        Very Long Outputs            0               0.0      Passed
            Empty Domains            0               0.0      Passed
Domains With Extra Spaces            0               0.0      Passed
            Empty Sources            0               0.0      Passed
Sources With Extra Spaces            0               0.0      Passed

In [48]:
# Save the quality check summary

output_path = (
    "../output/reports/"
    "quality_check_summary.csv"
)

quality_summary.to_csv(
    output_path,
    index=False
)

print(
    "Quality check summary saved successfully"
)

Quality check summary saved successfully